# Generated by Django 5.2.12 on 2026-06-18 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_index', models.IntegerField()),
                ('row_index', models.IntegerField()),
                ('row_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['table_index', 'row_index'],
            },
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='report_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pdfdocument',
            unique_together={('report_date', 'report_time')},
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['report_date', 'report_time'], name='scraper_pdf_report__711772_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['is_processed'], name='scraper_pdf_is_proc_20d20e_idx'),
        ),
        migrations.AddField(
            model_name='parsedtabledata',
            name='pdf_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_data', to='scraper.pdfdocument'),
        ),
        migrations.AlterUniqueTogether(
            name='parsedtabledata',
            unique_together={('pdf_document', 'table_index', 'row_index')},
        ),
    ]
