# Generated by Django 5.2.12 on 2026-06-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_parsedtabledata_pdfdocument_is_processed_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pdfdocument',
            name='scraper_pdf_report__711772_idx',
        ),
        migrations.RemoveIndex(
            model_name='pdfdocument',
            name='scraper_pdf_is_proc_20d20e_idx',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='uploaded_at',
        ),
    ]
