# Generated by Django 5.2.12 on 2026-06-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_remove_pdfdocument_scraper_pdf_report__711772_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pdfdocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
