# Generated by Django 5.2.12 on 2026-06-24 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_pdfdocument_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['report_date', 'report_time'], name='scraper_pdf_report__711772_idx'),
        ),
        migrations.AddField(
            model_name='pdfcomparison',
            name='base_pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_base', to='scraper.pdfdocument'),
        ),
        migrations.AddField(
            model_name='pdfcomparison',
            name='new_pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_new', to='scraper.pdfdocument'),
        ),
        migrations.AlterUniqueTogether(
            name='pdfcomparison',
            unique_together={('base_pdf', 'new_pdf')},
        ),
    ]
